kind: pipeline
name: test-latest-tag

trigger:
  event: push

steps:
- name: no-image-tag
  image: busybox:1.34.1
  commands:
   - ls

- name: okay-image
  image: busybox:1.34.1
  commands:
   - ls
---
kind: pipeline
name: another-working-pipeline

trigger:
  event: pull_request

steps:
- name: lint-helm-charts
  image: quay.io/helmpack/chart-testing:v3.8.0