# Compliant deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev
  labels:
    app: nginx
    env: dev
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    env: stg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.3.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vital-deployment-stg
  labels:
    app: nginx
    env: stg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vital-deployment
  template:
    metadata:
      labels:
        app: vital-deployment
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        ports:
        - containerPort: 80
      - name: important-image
        image: vital-image:latest
        ports:
        - containerPort: 80