# Non-compliant deployments
# metadata.labels.env is not one of {"dev", "stg", "prd"}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stg
  labels:
    app: nginx
    env: staging
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
# Non-compliant deployment: image tagged latest for "prd" env
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: prd
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
# Non-compliant deployment: no metadata.labels.env
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stg
  labels:
    app: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.3.2
        ports:
        - containerPort: 80